language: cpp
compiler:
# - clang
  - gcc
sudo: required
dist: trusty
cache: apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - cppcheck
      - qtbase5-dev
      - libqt5opengl5-dev
      - clang-3.6
install:
  - mkdir build && cd build
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - git clone https://github.com/cginternals/glbinding.git
  - cd glbinding && mkdir build && cd build && cmake .. -DOPTION_BUILD_TOOLS=OFF
  - make && sudo make install
  - cd ../..
before_script:
  - cppcheck ../utilgpu
script:
  - cmake .. -DCLANG_FORMAT=OFF -DBUILD_GL=ON -DBUILD_QT=ON
  - make && sudo make install && make test
