language: cpp
compiler:
  - clang
  - gcc
dist: bionic
cache: apt
addons:
  apt:
    packages:
      - cppcheck
      - xorg-dev
      - libglu1-mesa-dev
      - libglm-dev
      - libglbinding-dev
      - libglfw3-dev
install:
  - wget https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-linux-Release.zip
  - unzip -u -q glslang-master-linux-Release.zip
  - cd ..
  - export PATH=${TRAVIS_BUILD_DIR}/glslang/bin:$PATH
  - glslangValidator --version
before_script:
  - cppcheck ../utilgpu
script:
  - cmake .. -DCLANG_FORMAT=OFF -DBUILD_GL=ON -DBUILD_QT=ON -DBUILD_WINDOW=ON
  - make && make test
  - glslangValidator ../utilgpu/gl/shader/*
