language: cpp
compiler:
  - clang
  - gcc
dist: bionic
cache: apt
addons:
  apt:
    packages:
      - cppcheck
      - xorg-dev
      - libglu1-mesa-dev
      - libglm-dev
      - libglbinding-dev
      - libglfw3-dev
install:
  - mkdir build && cd build
  - svn checkout https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/Linux
  - cd Linux && ./install
  - cd ..
before_script:
  - cppcheck ../utilgpu
script:
  - cmake .. -DCLANG_FORMAT=OFF -DBUILD_GL=ON -DBUILD_QT=ON -DBUILD_WINDOW=ON
  - make && make test
  - glslangValidator ../utilgpu/gl/shader/*
